plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/jamesmartinmini/costar-deals"
publishOrigin = "config"
commandOrigin = "config"
command = "echo 'Deploying...'"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]